[toolchain]
channel = "nightly"

[package]
name = "chess_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.8"
color-eyre = "0.6.5"
enum-map = "3.1.0"
rand = "0.10.2"
thiserror = "2.0.21"

[lints.clippy]
all = { level = "deny", priority = -1 }
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
cast_sign_loss = "warn"
cast_lossless = "warn"
integer_division = "warn"
module_inception = "allow"
undocumented_unsafe_blocks = "deny"
multiple_unsafe_ops_per_block = "deny"

[lints.rust]
unsafe_op_in_unsafe_fn = "warn"